name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?palette=github-light
            dist/github-snake-dark.svg?palette=github-dark

      - name: Clean SVG Progress Bar & Adjust ViewBox
        run: |
          python -c 'import glob, re; [open(f,"w",encoding="utf-8").write(re.sub(r"viewBox=\"0 0 ([0-9.]+) [0-9.]+\"", r"viewBox=\"0 0 \1 114\"", re.sub(r"<rect class=\"u [^\"]*\"[^>]*/>", "", open(f,"r",encoding="utf-8").read()))) for f in glob.glob("dist/*.svg")]'

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animation [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


