name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?palette=github-light
            dist/github-snake-dark.svg?palette=github-dark

      - name: Clean SVG Progress Bar & Adjust ViewBox
        run: |
          python -c '
          import glob, re
          for f in glob.glob("dist/*.svg"):
              with open(f, "r", encoding="utf-8") as file:
                  data = file.read()
              data = re.sub(r"<rect class=\"u [^\"]*\"[^>]*/>", "", data)
              data = re.sub(r"viewBox=\"0 0 848\.6 \d+(\.\d+)?\"", "viewBox=\"0 0 848.6 114\"", data)


